# Generated by Django 3.1.3 on 2020-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=150, verbose_name='Kategoria:'),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_name',
            field=models.CharField(max_length=150, verbose_name='Nazwa dania:'),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena:'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='r_address',
            field=models.CharField(max_length=255, verbose_name='Adres:'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='r_name',
            field=models.CharField(max_length=150, verbose_name='Restauracja:'),
        ),
    ]
