# Generated by Django 3.1.3 on 2020-11-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='food_images'),
        ),
    ]
