# Generated by Django 3.1.3 on 2020-11-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20201106_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='f_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.category', verbose_name='Kategoria:'),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Restauracja:'),
        ),
    ]
