# Generated by Django 3.1.3 on 2020-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20201127_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Posiłek', 'verbose_name_plural': 'Posiłki'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restauracja', 'verbose_name_plural': 'Restauracje'},
        ),
        migrations.AddField(
            model_name='foodimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='food-thumbnails'),
        ),
    ]
