# Generated by Django 3.1.3 on 2020-12-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201204_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ManyToManyField(to='restaurants.Restaurant'),
        ),
    ]
