# Generated by Django 3.1.3 on 2020-12-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_category_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
    ]
