# Generated by Django 3.1.3 on 2020-11-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20201129_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food',
            new_name='category',
        ),
    ]
