# Generated by Django 3.1.3 on 2020-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20201109_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='adres', max_length=255, verbose_name='Adres:'),
        ),
    ]
