# Generated by Django 3.1.3 on 2020-12-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20201207_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.food', verbose_name='Posiłek'),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='food_images', verbose_name='Obraz'),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='food-thumbnails', verbose_name='Miniatura'),
        ),
    ]
