# Generated by Django 3.1.3 on 2020-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=150, verbose_name='Restauracja:')),
        ),
    ]
