# Generated by Django 3.1.3 on 2020-12-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='ig',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
