# Generated by Django 3.1.3 on 2020-12-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20201210_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='food_qr_codes'),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kalorie'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ig',
            field=models.CharField(blank=True, max_length=50, verbose_name='Indeks glikemiczny'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nazwa dania'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Restauracja'),
        ),
    ]
