# Generated by Django 3.1.3 on 2020-12-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurant-default.png', upload_to='restaurant_logos'),
        ),
    ]
