# Generated by Django 3.1.3 on 2020-12-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
