# Generated by Django 3.1.3 on 2021-01-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
    ]
