# Generated by Django 3.1.3 on 2021-01-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_remove_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(to='restaurants.Category'),
        ),
    ]
