# Generated by Django 3.1.3 on 2020-12-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_auto_20201218_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='restaurant',
            new_name='food',
        ),
    ]
