# Generated by Django 3.1.3 on 2020-11-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201127_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.CharField(default='miasto', max_length=60, verbose_name='Miasto:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(default='ulica', max_length=60, verbose_name='Ulica:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('PL', 'Polska')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(default='0/0', max_length=60, verbose_name='Nr bloku/mieszkania | domu:'),
        ),
    ]
