# Generated by Django 3.1.3 on 2020-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201110_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adres (Ulica nr domu/mieszkania, miejscowość, kraj:'),
        ),
    ]
