# Generated by Django 3.1.3 on 2020-12-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201205_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
