# Generated by Django 3.1.3 on 2020-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201201_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(max_length=60, verbose_name='Nr mieszkania:'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=60, verbose_name='Nr bloku/domu:'),
        ),
    ]
