# Generated by Django 3.1.3 on 2020-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201205_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_district',
            field=models.CharField(blank=True, max_length=120, verbose_name='Dzielnica'),
        ),
    ]
