# Generated by Django 3.1.3 on 2020-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201115_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=500, upload_to='qr_codes'),
        ),
    ]
