# Generated by Django 3.1.3 on 2020-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201201_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=60, verbose_name='Ulica:'),
        ),
    ]
