# Generated by Django 3.1.3 on 2020-12-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201201_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Adresy użytkowników'},
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nr mieszkania:'),
        ),
    ]
