# Generated by Django 3.1.3 on 2021-01-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201209_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='UserDeliveryInformation',
        ),
    ]
