# Generated by Django 3.1.3 on 2020-11-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201129_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address1',
            field=models.CharField(default='Kraków', editable=False, max_length=60, verbose_name='Miasto:'),
        ),
    ]
