# Generated by Django 3.1.3 on 2021-01-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210114_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeliveryinformation',
            old_name='address1',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userdeliveryinformation',
            old_name='address2',
            new_name='street',
        ),
    ]
