# Generated by Django 3.1.3 on 2020-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201117_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Kraków', max_length=255, verbose_name='Miasto: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Polska', max_length=255, verbose_name='Kraj :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(default=None, max_length=255, verbose_name='Nr domu, lub bloku/mieszkania: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default=None, max_length=255, verbose_name='Ulica: '),
        ),
    ]
