# Generated by Django 3.1.3 on 2020-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201130_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Polska', editable=False, max_length=60),
        ),
    ]
