# Generated by Django 3.1.3 on 2020-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201117_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.CharField(default=0, max_length=255, verbose_name='Nr domu, lub bloku/mieszkania: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default=0, max_length=255, verbose_name='Ulica: '),
        ),
    ]
