# Generated by Django 3.1.3 on 2020-12-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201130_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Address',
        ),
    ]
