# Generated by Django 3.1.3 on 2020-11-29 17:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0006_auto_20201129_1309'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OTWARTE', 'Otwarto nowe zamówienie'), ('ZŁOŻONE', 'Zamówienie przyjęte'), ('PRZYGOTOWYWANIE', 'Zamówienie przygotowywane'), ('WYSŁANE', 'Zamówienie wysłane'), ('ZREALIZOWANE', 'Zamówienie zrealizowane')], default='OTWARTE', max_length=15)),
                ('date_placed', models.DateField(default=datetime.datetime(2020, 11, 29, 17, 40, 25, 755272, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
            ],
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.food')),
            ],
        ),
    ]
