# Generated by Django 3.1.3 on 2020-11-18 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0005_auto_20201118_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('BRAK', 'Nie złożono zamówienia'), ('ZŁOŻONE', 'Zamówienie przyjęte'), ('PRZYGOTOWYWANIE', 'Zamówienie przygotowywane'), ('WYSŁANE', 'Zamówienie wysłane'), ('ZREALIZOWANE', 'Zamówienie zrealizowane')], default='BRAK', max_length=15)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Restauracja:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik:')),
            ],
        ),
    ]
