# Generated by Django 3.1.3 on 2020-12-01 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ilość:'),
        ),
    ]
