# Generated by Django 3.1.3 on 2020-11-29 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201129_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_placed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
