# Generated by Django 3.1.3 on 2020-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='order_qrcodes'),
        ),
    ]
