# Generated by Django 3.1.3 on 2020-12-03 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Koszyk', 'verbose_name_plural': 'Koszyki'},
        ),
        migrations.AlterModelOptions(
            name='cartline',
            options={'verbose_name': 'Produkty w koszyku', 'verbose_name_plural': 'Produkty w koszyku'},
        ),
        migrations.AddField(
            model_name='cartline',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
