# Generated by Django 3.1.3 on 2020-12-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_cartline_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('NOWE', 'Utworzono nowe zamówienie'), ('ZŁOŻONE', 'Zamówienie przyjęte'), ('PRZYGOTOWYWANIE', 'Zamówienie przygotowywane'), ('WYSŁANE', 'Zamówienie wysłane'), ('DOSTARCZONE', 'Zamówienie dostarczone, zrealizowne'), ('ANULOWANE', 'Zamówienie anulowane')], default='NOWE', max_length=15),
        ),
    ]
