# Generated by Django 3.1.3 on 2020-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201204_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('NOWE', 'Utworzono nowe zamówienie'), ('PRZYJĘTE', 'Zamówienie przyjęte'), ('PRZYGOTOWYWANIE', 'Zamówienie przygotowywane'), ('WYSŁANE', 'Zamówienie wysłane'), ('DOSTARCZONE', 'Zamówienie dostarczone, zrealizowne'), ('ANULOWANE', 'Zamówienie anulowane')], default='NOWE', max_length=15),
        ),
    ]
