# Generated by Django 3.1.3 on 2020-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201204_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('NEW', 'Utworzono nowe zamówienie'), ('ACCEPTED', 'Zamówienie przyjęte'), ('BEING PREPARED', 'Zamówienie przygotowywane'), ('SENT', 'Zamówienie wysłane'), ('DELIVERED', 'Zamówienie dostarczone, zrealizowne'), ('CANCELLED', 'Zamówienie anulowane')], default='NEW', max_length=15),
        ),
    ]
