# Generated by Django 3.1.3 on 2020-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20201204_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOWE', 'Oczekuje na przyjęcie'), ('PRZYJĘTE', 'Zamówienie przyjęte.'), ('ZREALIZOWANE', 'Zamówienie zrealizowane')], default='NOWE', max_length=15, verbose_name='Status zamówienia'),
        ),
    ]
