# Generated by Django 3.1.3 on 2020-12-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201205_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_placed'], 'verbose_name': 'zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
