# Generated by Django 3.1.3 on 2020-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Całkowita kwota zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Całkowita kwota zamówienia: '),
        ),
    ]
