# Generated by Django 3.1.3 on 2020-12-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_food_description'),
        ('orders', '0017_auto_20201209_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.food')),
            ],
        ),
        migrations.RenameModel(
            old_name='CartLine',
            new_name='CartItems',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='orders.OrderItem'),
        ),
    ]
