# Generated by Django 3.1.3 on 2020-12-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_food_description'),
        ('orders', '0018_auto_20201209_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Oczekujące na przyjęcie'), ('ACCEPTED', 'Zamówienie przyjęte'), ('BEING PREPARED', 'Zamówienie przygotowywane'), ('SENT', 'Zamówienie wysłane'), ('DELIVERED', 'Zamówienie dostarczone, zrealizowne'), ('CANCELLED', 'Zamówienie anulowane')], default='NEW', max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartLine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.food'),
        ),
    ]
