# Generated by Django 3.1.3 on 2020-12-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_food_description'),
        ('orders', '0020_auto_20201209_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='product',
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurants.food'),
        ),
    ]
