# Generated by Django 3.1.3 on 2020-12-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderline_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Koszt'),
        ),
    ]
