# Generated by Django 3.1.3 on 2020-12-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20201209_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPriceOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('sum_of_products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderline')),
            ],
        ),
    ]
