# Generated by Django 3.1.3 on 2020-12-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_totalpriceorderline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalPriceOrderLine',
        ),
    ]
