# Generated by Django 3.1.3 on 2020-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_delete_totalpriceorderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Całkowita wartość zamówienia'),
        ),
    ]
