# Generated by Django 3.1.3 on 2020-12-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20201209_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOWE', 'Oczekuje na przyjęcie'), ('PRZYJĘTE', 'Zamówienie przyjęte.'), ('PRZYGOTOWYWANE', 'W trakcie przygotowania'), ('WYSŁANE', 'Zamówienie wysłane'), ('ZREALIZOWANE', 'Zamówienie dostarczone, zrealizowane')], default='NOWE', max_length=15, verbose_name='Status zamówienia'),
        ),
    ]
