# Generated by Django 3.1.3 on 2021-01-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20201213_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address2',
            new_name='address2',
        ),
    ]
